name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: SpicyPizza/create-envfile@v1.0
      with:
        # complete the environment variables
        envkey_ENVIRONMENT: "staging"
        file_name: .env

    - name: Check .env file
      run: |
        cat .env
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Build the devenv shell and run any pre-commit hooks
      run: devenv test